/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UTSbdl;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ncahy
 */
public class Pelanggan extends javax.swing.JFrame {

    private final String[] columns = {"nama", "nomor antrian"};
    private final ArrayList<String[]> dataList = new ArrayList<>();
    Connection conn;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/UTSbdl";
    String user = "postgres";
    String password = "codotganteng";
    private String selectedIdPaket;

    public final void getAllData() {
        try {
            dataList.clear();
            String sql = "SELECT p.nama, t.id_transaksi "
                    + "FROM pelanggan p "
                    + "LEFT JOIN transaksi t ON p.id_pelanggan = t.id_pelanggan";
            conn = DriverManager.getConnection(koneksi, user, password);
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.executeQuery();
            final ResultSet data = ps.getResultSet();
            while (data.next()) {
                final String[] row = new String[]{
                    data.getString("nama"),
                    data.getString("id_transaksi")};
                dataList.add(row);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Creates new form Uts
     */
    public final void refreshModel() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        for (String[] data : dataList) {
            model.addRow(data);
        }
        Table.setModel(model);
    }

    /**
     * Creates new form Pelanggan
     */
    public Pelanggan() {
        try {

            conn = DriverManager.getConnection(koneksi, user, password);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        initComponents();
        this.getAllData();
        this.refreshModel();
        selectIdPemesanan();
    }

    public void selectIdPemesanan() {
        try {

            String sql = "Select nama_paket from paket_laundry";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet res = ps.executeQuery();
            while (res.next()) {
                String nama = res.getString("nama_paket");
                CBpaket.addItem(nama);
            }
//            connection.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFid = new javax.swing.JTextField();
        TFnama = new javax.swing.JTextField();
        TFalamat = new javax.swing.JTextField();
        TFtelpon = new javax.swing.JTextField();
        Bmemek = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CBpaket = new javax.swing.JComboBox<>();
        harga = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TFantrian = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        BbayarAja = new javax.swing.JButton();
        Badmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setText("ID");

        jLabel3.setText("nama");

        jLabel4.setText("alamat");

        jLabel5.setText("telpon");

        Bmemek.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        Bmemek.setText("PEMBAYARAN");
        Bmemek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmemekActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("DULLAH'S LAUNDRY");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("PILIH PAKET");

        CBpaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBpaketActionPerformed(evt);
            }
        });

        harga.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        harga.setText("HARGA PAKET");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("HARGA PAKET : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Rp");

        jLabel9.setText("Antrian");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table);

        BbayarAja.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        BbayarAja.setText("BAYAR AJA");
        BbayarAja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbayarAjaActionPerformed(evt);
            }
        });

        Badmin.setText("ADMIN");
        Badmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BadminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Badmin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bmemek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6)
                                        .addComponent(TFid)
                                        .addComponent(TFnama)
                                        .addComponent(TFalamat)
                                        .addComponent(TFtelpon)
                                        .addComponent(TFantrian, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CBpaket, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(BbayarAja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Badmin)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFtelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addComponent(CBpaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(harga)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TFantrian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(Bmemek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BbayarAja)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BmemekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmemekActionPerformed
        // TODO add your handling code here:
        PreparedStatement preparedStatement;
        
        try {
            String sql = "INSERT INTO pelanggan (id_pelanggan, nama, alamat, telpon) VALUES (?, ?, ?, ?)";

            preparedStatement = conn.prepareStatement(sql);

            preparedStatement.setString(1, TFid.getText());
            preparedStatement.setString(2, TFnama.getText());
            preparedStatement.setString(3, TFalamat.getText());
            preparedStatement.setString(4, TFtelpon.getText());

            preparedStatement.executeUpdate();

            String sql1 = "INSERT INTO transaksi (id_transaksi, total_harga, id_pelanggan, id_paket) VALUES (?, ?, ?, ?)";

            PreparedStatement preparedStatement1;
            preparedStatement1 = conn.prepareStatement(sql1);
            preparedStatement1.setString(1, TFantrian.getText());
            preparedStatement1.setString(2, harga.getText());
            preparedStatement1.setString(3, TFid.getText());
            preparedStatement1.setString(4, this.selectedIdPaket);

            preparedStatement1.executeUpdate();

            JOptionPane.showMessageDialog(this, "Lanjut ke pembayaran");
            this.getAllData();
            this.refreshModel();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal ditambahkan", "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
        Pembayaran frame1 = new Pembayaran();
        frame1.setVisible(true);


    }//GEN-LAST:event_BmemekActionPerformed

    private void CBpaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBpaketActionPerformed
//        try {
//            String query = "SELECT id_paket, harga_paket FROM paket_laundry WHERE nama_paket = ?";
//            PreparedStatement ps = conn.prepareStatement(query);
//            ps.setString(1, CBpaket.getSelectedItem().toString());
//            ResultSet res = ps.executeQuery();
//            while(res.next()){
//                //String hargaP = res.getString("harga_paket");
//                //harga.setText(hargaP);
//                String idPaket = res.getString("id_paket");        // Ambil id_paket
//                String hargaPaket = res.getString("harga_paket");  // Ambil harga_paket
//                
//                
//            }
//        }catch(Exception e){
//            System.out.println(e.getMessage());
//        }
        try {
            // Modifikasi query untuk mengambil id_paket dan harga_paket berdasarkan nama_paket
            String query = "SELECT id_paket, harga_paket FROM paket_laundry WHERE nama_paket = ?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, CBpaket.getSelectedItem().toString());  // Mengambil nama_paket dari ComboBox
            ResultSet res = ps.executeQuery();

            // Jika hasil ditemukan, ambil id_paket dan harga_paket
            while (res.next()) {
                String idPaket = res.getString("id_paket");        // Ambil id_paket
                String hargaPaket = res.getString("harga_paket");  // Ambil harga_paket

                // Simpan id_paket ke variabel atau elemen GUI sesuai kebutuhan
                this.selectedIdPaket = idPaket;  // Simpan id_paket ke variabel global (untuk digunakan saat input transaksi)

                // Set harga_paket ke TextField atau Label
                harga.setText(hargaPaket);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_CBpaketActionPerformed

    private void BbayarAjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbayarAjaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Pembayaran frame1 = new Pembayaran();
        frame1.setVisible(true);
    }//GEN-LAST:event_BbayarAjaActionPerformed

    private void BadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BadminActionPerformed
        // TODO add your handling code here:
        String inputPassword = JOptionPane.showInputDialog(this, "Masukkan password admin:");

        // Memeriksa apakah password benar
        if ("dullah".equals(inputPassword)) {
            JOptionPane.showMessageDialog(this, "Password benar! Akses ke form admin.");
            // Kode untuk membuka form admin di sini
            openAdminForm();
            this.dispose();
            Admin frame2 = new Admin();
            frame2.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Password salah!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

// Method untuk membuka form admin
    private void openAdminForm() {
        // Buat form admin baru
    }//GEN-LAST:event_BadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pelanggan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Badmin;
    private javax.swing.JButton BbayarAja;
    private javax.swing.JButton Bmemek;
    private javax.swing.JComboBox<String> CBpaket;
    private javax.swing.JTextField TFalamat;
    private javax.swing.JTextField TFantrian;
    private javax.swing.JTextField TFid;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFtelpon;
    private javax.swing.JTable Table;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
