/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UTSbdl;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ncahy
 */
public class Pembayaran extends javax.swing.JFrame {

    Connection conn;
    String antrian;
    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/UTSbdl";
    String user = "postgres";
    String password = "codotganteng";

    /**
     * Creates new form Pembayaran
     */
    private String generateNewId(Connection conn) throws SQLException {
        String newId = "PAY0001";  // ID awal jika belum ada data

        // Query untuk mendapatkan ID pembayaran terakhir
        String sql = "SELECT id_pembayaran FROM pembayaran ORDER BY id_pembayaran DESC LIMIT 1";
        PreparedStatement statement = conn.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery();

        if (resultSet.next()) {
            String lastId = resultSet.getString("id_pembayaran");
            System.out.println("ID terakhir dari database: '" + lastId + "'");  // Logging ID terakhir

            if (lastId != null && lastId.length() >= 4) {
                // Hapus spasi sebelum parsing
                lastId = lastId.trim(); // Menghapus spasi di awal dan akhir
                try {
                    int lastIdNumber = Integer.parseInt(lastId.substring(3));  // Ambil angka dari ID terakhir
                    lastIdNumber++;  // Increment ID
                    newId = "PAY" + String.format("%04d", lastIdNumber); // Format ke ID baru
                } catch (NumberFormatException e) {
                    System.out.println("Format ID tidak valid: " + lastId);
                    e.printStackTrace();
                }
            } else {
                System.out.println("ID terakhir tidak valid: " + lastId);
            }
        } else {
            System.out.println("Tidak ada ID pembayaran yang ditemukan, menggunakan ID default.");
        }

        resultSet.close();
        statement.close();

        return newId;
    }

    public Pembayaran() {
        try {

            conn = DriverManager.getConnection(koneksi, user, password);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFjumlahPembayaran = new javax.swing.JTextField();
        CBmetodePembayaran = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        BkonfirmasiPembayaran = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        Bsearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        namaLBL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hargaLBL = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        antrianLBL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        statusLBL = new javax.swing.JLabel();
        TFstatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("DULLAH'S LAUNDRY");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("PEMBAYARAN");

        jLabel2.setText("Metode Pembayaran");

        jLabel4.setText("Status Pembayaran");

        TFjumlahPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFjumlahPembayaranActionPerformed(evt);
            }
        });

        CBmetodePembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QRIS", "Cash" }));
        CBmetodePembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBmetodePembayaranActionPerformed(evt);
            }
        });

        jLabel5.setText("Jumlah Pembayaran");

        BkonfirmasiPembayaran.setBackground(new java.awt.Color(51, 255, 51));
        BkonfirmasiPembayaran.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        BkonfirmasiPembayaran.setText("KONFIRMASI PEMBAYARAN");
        BkonfirmasiPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkonfirmasiPembayaranActionPerformed(evt);
            }
        });

        jLabel7.setText("Masukkan ID");

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        Bsearch.setText("SEARCH");
        Bsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsearchActionPerformed(evt);
            }
        });

        jLabel6.setText("Nama");

        namaLBL.setText("-");

        jLabel9.setText("Harga");

        hargaLBL.setText("-");

        jLabel8.setText("No Antrian");

        antrianLBL.setText("-");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hargaLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(Bsearch))
                                        .addComponent(namaLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(107, 107, 107)))
                                .addGap(0, 115, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(52, 52, 52))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(92, 92, 92))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(antrianLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CBmetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TFstatus)
                                            .addComponent(TFjumlahPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(statusLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(124, 124, 124))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BkonfirmasiPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(269, 269, 269))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bsearch)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(namaLBL))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(hargaLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(antrianLBL))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBmetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFjumlahPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(statusLBL)
                    .addComponent(TFstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(BkonfirmasiPembayaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFjumlahPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFjumlahPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFjumlahPembayaranActionPerformed

    private void CBmetodePembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBmetodePembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBmetodePembayaranActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void BsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsearchActionPerformed
        // TODO add your handling code here:
        String query = "SELECT nama FROM pelanggan where id_pelanggan LIKE ?";
        try {

            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, "%" + id.getText() + "%");
            ps.execute();
            ResultSet rs = ps.getResultSet();
            while (rs.next()) {
                String nama = rs.getString("nama");
                namaLBL.setText(nama);

            }

            String query1 = "SELECT id_transaksi, total_harga FROM transaksi WHERE id_pelanggan LIKE ?";
            PreparedStatement ps1 = conn.prepareStatement(query1);
            ps1.setString(1, "%" + id.getText() + "%");
            ps1.execute();
            ResultSet rs1 = ps1.getResultSet();
            int harga = 0;
            String id_transaksi = "";
            while (rs1.next()) {
                harga = Integer.parseInt(rs1.getString("total_harga"));
                id_transaksi = rs1.getString("id_transaksi");
            }
            
            int hasil = harga;
            hargaLBL.setText(String.valueOf(hasil));
            
            System.out.println(id_transaksi);
            
            String query3 = "SELECT * FROM pembayaran WHERE id_transaksi = ? AND status_pembayaran = 'DP DULU'";
            PreparedStatement ps3 = conn.prepareStatement(query3);
            ps3.setString(1, id_transaksi);
            ps3.executeQuery();
            ResultSet rs2 = ps3.getResultSet();
            while (rs2.next()) {
                int jumlah_bayar = Integer.parseInt(rs2.getString("jumlah_bayar"));
                hasil = harga - jumlah_bayar;
                hargaLBL.setText(String.valueOf(hasil));
            }
            
            

            String query2 = "SELECT id_transaksi FROM transaksi where id_pelanggan LIKE ?";

            PreparedStatement ps2 = conn.prepareStatement(query2);
            ps2.setString(1, "%" + id.getText() + "%");
            ps2.execute();
            rs2 = ps2.getResultSet();
            while (rs2.next()) {
                antrian = rs2.getString("id_transaksi");
                antrianLBL.setText(antrian);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "error " + e.getMessage());

        }
    }//GEN-LAST:event_BsearchActionPerformed

    private void BkonfirmasiPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkonfirmasiPembayaranActionPerformed
          // TODO add your handling code here:
        PreparedStatement preparedStatement;
        CallableStatement cs;

        // Ambil nilai jumlah pembayaran sebagai string karena jumlah_bayar bertipe varchar
        String jumlahPembayaranBaru = TFjumlahPembayaran.getText(); // Pembayaran baru yang diinput
        String idTransaksi = antrianLBL.getText(); // ID transaksi dari antrian
        int totalHarga = Integer.parseInt(hargaLBL.getText()); // Total harga dari transaksi
           
        int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin melanjutkan pembayaran?", "Konfirmasi Pembayaran", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION){
            try {
            // Memulai transaksi
            conn.setAutoCommit(false);// Mematikan autocommit untuk manual commit

            // Mengecek total pembayaran sebelumnya
            String SqlTotalPembayaran = "SELECT COALESCE(SUM(CAST(jumlah_bayar AS INTEGER)), 0) AS total_pembayaran_sebelumnya FROM pembayaran WHERE id_transaksi = ?";
            preparedStatement = conn.prepareStatement(SqlTotalPembayaran);
            preparedStatement.setString(1, idTransaksi);
            ResultSet rs = preparedStatement.executeQuery();

            int totalPembayaranSebelumnya = 0;
            if (rs.next()) {
                totalPembayaranSebelumnya = rs.getInt("total_pembayaran_sebelumnya");
            }

            // Menghitung total pembayaran setelah pembayaran baru
            int totalPembayaranSekarang = totalPembayaranSebelumnya + Integer.parseInt(jumlahPembayaranBaru);

            // Mengecek apakah pembayaran sudah lunas atau masih DP
            String statusPembayaran;
            if (totalPembayaranSekarang >= totalHarga) {
                statusPembayaran = "Lunas";
            } else {
                statusPembayaran = "DP DULU";
            }

            // Menampilkan status pembayaran di form
            TFstatus.setText(statusPembayaran);

            // Insert pembayaran baru ke database
            String newIdPembayaran = generateNewId(conn); // Generate ID baru untuk pembayaran
            String sql = "INSERT INTO pembayaran (metode_pembayaran, jumlah_bayar, status_pembayaran, id_transaksi, id_pembayaran) VALUES (?, ?, ?, ?, ?)";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, CBmetodePembayaran.getSelectedItem().toString()); // Metode pembayaran
            preparedStatement.setString(2, jumlahPembayaranBaru); // Jumlah bayar (tipe varchar)
            preparedStatement.setString(3, statusPembayaran); // Status pembayaran
            preparedStatement.setString(4, idTransaksi); // ID transaksi
            preparedStatement.setString(5, newIdPembayaran); // ID pembayaran baru

            preparedStatement.executeUpdate(); // Eksekusi query insert
            conn.commit();
            // Menampilkan dialog konfirmasi Yes/No
              

        } catch (SQLException e) {
         
            try {
                // Jika terjadi error, rollback perubahan
                conn.rollback();
            } catch (SQLException rollbackEx) {
                rollbackEx.printStackTrace();
            }
            e.printStackTrace(); // Tampilkan error di console
            JOptionPane.showMessageDialog(null, "Data gagal ditambahkan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                // Mengembalikan autocommit ke true setelah transaksi selesai
                conn.setAutoCommit(true);
            } catch (SQLException finalEx) {
                finalEx.printStackTrace();
            }
        }
        }
        
    }//GEN-LAST:event_BkonfirmasiPembayaranActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Pelanggan frame1 = new Pelanggan();
        frame1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BkonfirmasiPembayaran;
    private javax.swing.JButton Bsearch;
    private javax.swing.JComboBox<String> CBmetodePembayaran;
    private javax.swing.JTextField TFjumlahPembayaran;
    private javax.swing.JTextField TFstatus;
    private javax.swing.JLabel antrianLBL;
    private javax.swing.JLabel hargaLBL;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel namaLBL;
    private javax.swing.JLabel statusLBL;
    // End of variables declaration//GEN-END:variables
}
